# permissions for end users to edit vehpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vehpod-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: piccolo
    app.kubernetes.io/part-of: piccolo
    app.kubernetes.io/managed-by: kustomize
  name: vehpod-editor-role
rules:
- apiGroups:
  - crd.piccolo.org
  resources:
  - vehpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.piccolo.org
  resources:
  - vehpods/status
  verbs:
  - get
