FROM python:3.10-slim AS builder

RUN apt-get update && apt-get -y install libgl1-mesa-glx libglib2.0-0 gcc g++ cmake
RUN pip install opencv-python dlib face-recognition
RUN apt-get -y install libgtk2.0-dev pkg-config

FROM python:3.10-slim

COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
#COPY --from=builder /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu
COPY --from=builder /usr/lib/aarch64-linux-gnu /usr/lib/aarch64-linux-gnu
COPY ./app /app

CMD ["python3", "/app/camera-test.py"]
